### ISSUE TITLE
SCEL 1840 Flights no Groundnet 2 Parkings

### ISSUE THREAD

**Issue by Portree-Kid** [terrasync/main#302]
Name :Arturo Merino Benitez Intl
Airlines :AAL ACA AFR AMX CMP DAL IBE KAL KLM LAN QFA TAM

**Comment by BecOzIcan** [comment]
Most likely overinflated LAN traffic. Update cancelled when they merged with TAM. Resulting LATAM had timetables all over the place and too big to handle (same as AAL DAL UAL)

**Comment by Portree-Kid** [comment]
2 Parkings still too few. Basically just testcase for FG Airports anyway.
