### ISSUE TITLE
KPIT Errors in Groundnet

### ISSUE THREAD

**Issue by Portree-Kid** [terrasync/main#325]
* Unconnected Runway Nodes 
* Overlapping Parkings

**Comment by Honu4** [comment]
I submitted an updated groundnet for KPIT. It passed all local checks, but it looked like it failed the Travis CI check. But then it was closed as merged? What is itʻs actual status?

**Comment by BecOzIcan** [comment]
Hey Douglas. Travis failed checks were not related to your groundnet which was OK so I merged it

Yves

________________________________

**Comment by Portree-Kid** [comment]
Sadly I haven’t got round to massaging Travis. Too many irons in the fire.
