### ISSUE TITLE
KORD bad runway definitions

### ISSUE THREAD

**Issue by legoboyvdlp** [terrasync/main#332]
KORD has invalid runways.

KORD defines a runway 10 in the threshold file. There isn't any such runway - there is 9L / 9R and 10L / 10C / 10R.

I believe this is the cause of an exception in the traffic manager, would be glad if this could be updated :)

**Comment by BecOzIcan** [comment]
KORD.threshold.xml updated and merged to groundweb 
Source Data https://www.faa.gov/air_traffic/publications/atpubs/aip_html/part3_ad_2.0_illinois.html

**Comment by legoboyvdlp** [comment]
Thanks!

**Comment by BecOzIcan** [comment]
Issue re investigated. 
Traffic Manager error comes from RWYUSE referencing runways whose designation does not exist in APT.DAT 

14L/32R  as well as 14R/32L no longer exist and are now taxiways
10C/28C, 10R/28L are new and not defined in APT hence cannot be used by AI traffic
10L/28R as indicated before is known in APT.DAT as 10/28; we can use/reference it in AI code for as long as using the old designation

That means RWYUSE should only reference 5 runways ie
27R/09L
27L/09R
10/28
04L/22R
04R/22L

I am pushing updated RWYUSE and THRESHOLDS files tonight
