### ISSUE TITLE
EPKT

### ISSUE THREAD

**Issue by gooneybird47** [terrasync/main#360]
Being updated

**Comment by gooneybird47** [comment]
I'm not sure whether to upload this one yet and would welcome your thoughts on it.

It is based on the new layout, which is not in FG, with a new runway and the old runway as a taxiway, this causing chaos with the AI traffic. Pushbacks are working but as soon as the AI reach the old runway/taxiway they grind to a halt with very few taking off, arrivals are working ok but only on the old runway.
Personally I would upload as it should be fine when the scenery is updated.

**Comment by BecOzIcan** [comment]
- . I have updated the wiki : 
"Traffic Manager uses a separate ICAO.threshold.xml file to determine where runways are (the space between each pair of thresholds in the file). The last node of a route ending on runway must be within the two thresholds for the aircraft to initiate its take-off. This is key for displaced thresholds. If the route does not end within thresholds, AI aircrafts will simply stop and queue at the entrance of the runway"

- I have confirmed the current EPKT.threshold.xml in Terrasync contains the old runway data 

- I have updated and merged EPKT.threshold.xml with the new runway data, taken from https://www.ais.pansa.pl/aip/pliki/EP_AD_2_EPKT_en.pdf

- I ll send you a copy of the file by email so you can test on your machine until the next groundweb/terrasync resync

**Comment by gooneybird47** [comment]
Worked a treat.
