### ISSUE TITLE
KRDU

### ISSUE THREAD

**Issue by wkitty42** [terrasync/main#366]
i'm adding GA parking to KRDU for my GA Ai Traffic... i'm also cleaning up the ground net and refining it a little...

- started with existing WIP of KRDU ground net
- editing it with portreekid's new tool
- have added ~22 GA parking places... most are currently reserved for ficticious(?) LandMark Aviation that used to be based at KRDU
- refining some taxiways

**Comment by Honu4** [comment]
Dude, I'm so sorry. I didn't see this until just now. Don't know how I missed it. I submitted #640 a couple of days ago.

**Comment by wkitty42** [comment]
> Dude, I'm so sorry. I didn't see this until just now. Don't know how I missed it. I submitted #640 a couple of days ago.

i saw that... it is fine... i'll just start over with this updated one from you and carry on... hopefully your's is better than the existing default one with commercial craft parking in definitely wrong places...

i'm not even going to worry about this issue being closed by the merge, either... when i get (back) to the point, i'll just open another one... no big deal...
