### ISSUE TITLE
NavData

### ISSUE THREAD

**Issue by legoboyvdlp** [terrasync/main#504]
Is this repository able to technically process NavData contributions? This mechanism could be used to update airport .dat files. For instance, Jan Mayen is long overdue a fix, as the apt.dat file is badly misplaced, but the TerraSync scenery has the correct airport location.

**Comment by Portree-Kid** [comment]
Technically it would be possible. You would basically upload apt.dat snippets. The correct repo is groundweb.

**Comment by Portree-Kid** [comment]
https://github.com/Portree-Kid/groundweb/issues

**Comment by legoboyvdlp** [comment]
Thank you
