### ISSUE TITLE
OMAA

### ISSUE THREAD

**Issue by BecOzIcan** [terrasync/main#532]
Revamping OMAA Abu Dhabi groundnet (and WED layout at the same time)

**Comment by BecOzIcan** [comment]
Groundnet and related files merged. 

![image](https://user-images.githubusercontent.com/49523106/108849158-f4f56800-7635-11eb-8a45-e098459ab74a.png)


Putting the final touches to the WED Layout. Will submit to X-Plane Gateway in the coming days. 

Will make terrain available for download via FG Scenery Forum

![image](https://user-images.githubusercontent.com/49523106/108848787-86b0a580-7635-11eb-8aa8-3f64a32fe3c6.png)

**Comment by UmKhammas9** [comment]
Yves are going to anything about OMAA terrain because it was about 4 months now
