### ISSUE TITLE
CYYC is missing runway 17R/35R

### ISSUE THREAD

**Issue by Honu4** [terrasync/main#592]

**Comment by BecOzIcan** [comment]
This data is stored in APT.DAT and not updated centrally as far as I know. 

If the current WED layout includes the missing runway you can generate an apt.dat from it and then use in your custom scenery folder.

Although AI aircrafts will then 'see' the extra runway when running the simulator, I don't believe FG Airport will. So attempts to add groundnet routes from/to that runway should fail FGA validation. 

Nvertheless, assuming you have genreated a dedicated apt.dat for this particular airport and placed it in your custom scenery folder you may then be able to change the FGA folders setting to point to your custom APT.

Never tried it myself but I assume this means FGA would no longer see the layout of any other airport given it would no longer read the global apt.dat ? 

![image](https://user-images.githubusercontent.com/49523106/118234879-4d226480-b4d7-11eb-996f-8a6126356a41.png)

**Comment by BecOzIcan** [comment]
On second thought it may not be wise to distribute via Terrasync a groundnet built this way as it would still reference nodes on a runway which would not exist in the underlying global APT.DAT.

I would recommend posting to the Developers List

**Comment by wkitty42** [comment]
On 5/14/21 5:37 AM, Yves Tolosa-Joas wrote:
> On second thought it may not be wise to distribute via Terrasync a groundnet 
> built this way as it would still reference nodes on a runway which would not 
> exist in the underlying global APT.DAT

this is one reason why i work with what we have instead of trying to do things 
with more accurate up-to-date IRL layouts...

when FG does finally get apt.dat and other related data files updated, we will 
just have to go back and fix these ground nets and parking... that would have to 
be done anyway...
