### ISSUE TITLE
KJFK ILS Localizers are wrong

### ISSUE THREAD

**Issue by Honu4** [terrasync/main#593]
It appears that the Localizers are facing the wrong way. At any rate, KJFK needs some work that I cannot do. I've never been able to get WED set up to edit the airports. 

<img width="1061" alt="Screen Shot 2021-05-13 at 12 48 43 PM" src="https://user-images.githubusercontent.com/67807217/118196955-a4e2a200-b3e9-11eb-85a3-389aba22d182.png">
<img width="1440" alt="Screen Shot 2021-05-13 at 12 42 57 PM" src="https://user-images.githubusercontent.com/67807217/118196767-4a494600-b3e9-11eb-909c-d2b8b82c2f5f.png">
<img width="1440" alt="Screen Shot 2021-05-13 at 12 43 45 PM" src="https://user-images.githubusercontent.com/67807217/118196778-4f0dfa00-b3e9-11eb-81ae-98fb0e2b8459.png">
<img width="1440" alt="Screen Shot 2021-05-13 at 12 44 37 PM" src="https://user-images.githubusercontent.com/67807217/118196783-503f2700-b3e9-11eb-845d-29f787af0142.png">
<img width="1440" alt="Screen Shot 2021-05-13 at 12 45 17 PM" src="https://user-images.githubusercontent.com/67807217/118196793-51705400-b3e9-11eb-957b-6d98ce5a3747.png">

**Comment by BecOzIcan** [comment]
AFAIK this data is stored in the global APT DAT and cannot be varied by WED but I have seen some discussions on the Forums about sending requests to update particular NAVDATA

**Comment by wkitty42** [comment]
On 5/14/21 3:13 AM, Yves Tolosa-Joas wrote:
> AFAIK this data is stored in the global APT DAT and cannot be varied by WED but 
> I have seen some discussions on the Forums about sending requests to update 
> particular NAVDATA

someone was doing some work several weeks ago to correct antennas that were 
visually pointing incorrectly... there was discussion on the discord as well as 
the mailing list... i'm not sure about the status of those fixes, though...
