### ISSUE TITLE
LIMC

### ISSUE THREAD

**Issue by BecOzIcan** [terrasync/main#639]
Groundnet update started for LIMC Milan Mapensa

**Comment by sfrsfrsfr** [comment]
that's unfortunate, see #536

**Comment by BecOzIcan** [comment]
OH Fudge ! Why is this not showing up on my list ? Some sort of max 20 per page I guess ?
Thanks for noticing. 

I ll still upload mine tonight, it is a basic as part of the troubleshooting of AI errors. Feel absolutely free to submit yours on top of it whenever you're ready, I have no particular emotional attachment to this one :-)

**Comment by sfrsfrsfr** [comment]
no big deal. the terminal building is misplaced & the wrong size. i've resized it to somehow rl dimensions but haven't submitted it yet. and there's another group scenery objects (jetways, animated jetways etc.) that need to be relocated which i didn't do.

as you'll update the groundnet i'll submit the modifed terminal soon.

**Comment by BecOzIcan** [comment]
Team Work ! That sounds like a good plan to me. Groundnet / Threshold and Runway Use files should be merged within the next hour.

Take care 
Ian

**Comment by sfrsfrsfr** [comment]
fyi, the new groundnet contains a bunch of duplicate edges/segments

0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:0->166
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:166->0
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:1->167
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:167->1
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:2->168
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:168->2
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:3->169
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:169->3
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:4->170
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:170->4
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:5->171
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:171->5
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:6->172
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:172->6
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:7->173
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:173->7
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:8->174
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:174->8
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:9->175
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:175->9
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:10->176
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:176->10
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:11->177
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:177->11
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:12->178
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:178->12
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:13->179
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:179->13
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:14->180
    0.40 [WARN]:navaid     LIMC ground-net: skipping duplicate edge:180->14

did you do rework the existing one? if not then this could be an issue with fga

**Comment by BecOzIcan** [comment]
These look like the errors we had in the original groundnet. 

The version I pushed 3 days ago does not trigger any error on my console.

Still I can see this new groundnet has not yet been sync'd to Terrasync so if you running your scenery out of terrasync you still get the bugged groudnet.

An easy way to confirm is to grab the LIMC in Groundweb and put in in your custom scenery (with higher priority than Terrasync, to bypass the old version) and see if you still get these errors 

![image](https://user-images.githubusercontent.com/49523106/121656960-5822e180-cae3-11eb-881a-c5b652abbde2.png)

**Comment by sfrsfrsfr** [comment]
ah, i missed a copy operation. all is well

**Comment by BecOzIcan** [comment]
You got me very nervous for a second here. :-) 

I ll still check with Keith the frequency of Terrasync updates, the KSEA I pushed 6 days ago is still not in there.
