### ISSUE TITLE
Groundnets being updated

### ISSUE THREAD

**Issue by gooneybird47** [terrasync/main#650]
Here's a list of my old groundnets that are showing errors in the Broken Airports list, I'll be gradually updating these.
Please let me know you are working on, or intend to work on, any of them so I can remove them from my to do list, thanks.

EGAA  - Fixed
EGAC - Fixed
EGBB  -  Fixed
EGGP - Fixed
EGGW - Fixed
EGHI - Fixed
EGJB  -  Fixed
EGJJ  -  Fixed
EGPH - Fixed
EGSH - Fixed
EHBK - Fixed
EKAH - Fixed
ENRY - Fixed
EPKK - Fixed
GCFV - Fixed
GCLP - Fixed
GCRR - Fixed
GCTS - Fixed
GMMX - Fixed
LEAL - Fixed
LFBE - Fixed
LFMU - Fixed
LIME - Fixed
LIPH  -  Fixed
LIRP - Fixed
LIRZ - Fixed
LROP - Fixed

**Comment by gooneybird47** [comment]
All errors fixed.

Some groundnets will be revisited after the current AI problems are fixed.

**Comment by BecOzIcan** [comment]
Thank a lot for all this work Brett

**Comment by gooneybird47** [comment]
I do have a few half finished ones that I'll get finished one day but taking a break and going back to the AI models for now.
