### ISSUE TITLE
Disused Runways

### ISSUE THREAD

**Issue by gooneybird47** [terrasync/main#664]
Several of the airports I'm updating have disused runways now being used as taxiways or parking (GCFV, EGSH, EGPH) but they are still flagged as runways in Apt.dat.
When using FGA nodes placed on these are marked as "On Runway", removing the tags is easy enough but then of course they fail the FGA check and I'm assuming they will also fail the Travis checks.

How do you want these uploaded?

**Comment by BecOzIcan** [comment]
**Long Option** 

1. Mark the nodes "on runway" to satisfy the FGA validation 
2. Run the FGA Check 
3. Use the Eye Icon on the bottom right to expose and note down the ID of the nodes you need to change 
![image](https://user-images.githubusercontent.com/49523106/122254689-b18a7680-cf10-11eb-8d35-6e32870fa7fd.png)

4. Export your file to the temporary folder 
5. Edit the XML in notepad++ to remove the "on runway" tag of the nodes you marked down 
6. Upload via groundweb

It would also be good idea to update the thresholds.xml to remove these old runways thresholds so AI aircrafts no longer "see" th runway. 

**Short Option** 

Export and Edit in Taxidraw (where you can remove the physical runway), validate and submit via groundweb.

I have raised a request to get the runway calculated from the Threshold file and not the APT DAT so in the future, removing the thresholds of the disused runway will mean the "on runway" test will pass. 

Cheers
Ian

**Comment by gooneybird47** [comment]
Thanks Ian, will do that or a variation of ;)

**Comment by gooneybird47** [comment]
Removing the disused runway from GCFV  threshold.xml currently doesn't stop the AI using the disused runway but a runway use file does.

Considering the fact that GCFV is now in real life a single runway airport do you want a temporary rwyuse.xml file uploaded with the groundnet and threshold files until there are updates in place to correct the problem or are we just going to leave it as it is for now.

Also found a near complete ground net for GCLP on my computer that I'll add to my list.

**Comment by BecOzIcan** [comment]
Interesting finding on THR

You know my approach, stick to real data cause eventually the outdated one (APT.DAT) will get fixed so if ok with you, please submit updates for the 3 files (groundnet, thresholds and runwayuse) with the single runway.

Take care

**Comment by gooneybird47** [comment]
Do you want want this issue closed or left open for future reference?

**Comment by BecOzIcan** [comment]
I ll link and close :-)
