### ISSUE TITLE
LEBL runway change

### ISSUE THREAD

**Issue by nicolandu** [terrasync/main#960]
RWY 07-> RWY 06
RWY 25 ->RWY 24

**Comment by wkitty42** [comment]
this is not the proper place to report these changes... we, as in FG, cannot easily change/fix them... they require updates to the airport on the x-plane gateway... then FG will pull those updates and rebuild the scenery at some point in time... WS3 should make this easier when it finally becomes available... it still takes months and months for a scenery rebuild, though, but it is faster, now, than it was with the old tools when WS2 was originally built...

this issue should be closed with something like "not planned"...
